# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [14]:
df["Legendary"].unique()

array([False,  True])

In [7]:
#Assumption: dragon mean(HP) > Grass mean(HP)
# Hypotheses: H0: Dragon mean(HP) <= Grass mean(HP)
# H1: Dragon mean(HP) > Grass mean(HP)
# Statisticql testdf: TWO SAMPLE T-TEST: compare 2 groups means
dragon_hp = df[df['Type 1'] == "Dragon"]["HP"]
grass_hp = df[df['Type 1'] == "Grass"]["HP"]
statistic, p_value = st.ttest_ind(dragon_hp, grass_hp, equal_var = False, alternative = "greater")
if p_value < 0.05:
    print("We reject H0")
else:
    print("fail to reject H0")

We reject H0

## H0 is rejected, there is evidence that Dragon mean(HP) is greater than Grass mean(HP).

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [13]:
# Assumption: Legendary Pokemons have different stats than Non_legendary pokemon. We compare the means of different stats for 2 groups. We use 2-sample T-test
# H0: number of stats1 = number os stats2
# H1: number of stats1 != number os stats2
#Conclusion: After running the hypothesis tests, we conlcude that there is insufficient evidence thet the stats are the same for the 2 groups of Pokemons

In [21]:
legendary_hp = df[df["Legendary"] == True]['HP']
non_legendary_hp = df[df["Legendary"] == False]['HP']
legendary_Attack = df[df["Legendary"] == True]['Attack']
non_legendary_Attack = df[df["Legendary"] == False]['Attack']
legendary_Defense = df[df["Legendary"] == True]['Defense']
non_legendary_Defense = df[df["Legendary"] == False]['Defense']
legendary_sp_atk = df[df["Legendary"] == True]['Sp. Atk']
non_legendary_sp_atk = df[df["Legendary"] == False]['Sp. Atk']
legendary_sp_def = df[df["Legendary"] == True]['Sp. Def']
non_legendary_sp_def = df[df["Legendary"] == False]['Sp. Def']
legendary_Speed = df[df["Legendary"] == True]['Speed']
non_legendary_Speed = df[df["Legendary"] == False]['Speed']
legendary_gen= df[df["Legendary"] == True]['Generation']
non_legendary_gen = df[df["Legendary"] == False]['Generation']

#HP stats
statistic_hp, p_value_hp = st.ttest_ind(legendary_hp, non_legendary_hp, equal_var = False, alternative = "two-sided")
if p_value_hp < 0.05:
    print("For HP stats, reject H0: ")
    print(" --> there is insufficient evidence that the HP means of the 2 groups are the same")
else:
    print("Fail to reject H0 for stat HP: -->there is enough evidence that the means of the 2 groups are different")
print('-----------------------------------------------------------------------------------------------------------------')
#----------------------------------------------------------------------------------------------------------------------#
# 2. Attack stats
statistic_attack, p_value_attack = st.ttest_ind(legendary_Attack, non_legendary_Attack, equal_var = False, alternative = "two-sided")
if p_value_attack < 0.05:
    print("For Attack stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same")
else:
    print("Fail to reject H0 for stat Attack: -->there is enough evidence that the means of the 2 groups are different")
print('-----------------------------------------------------------------------------------------------------------------')
#----------------------------------------------------------------------------------------------------------------------#
#3. Defense
statistic_Defense, p_value_Defense = st.ttest_ind(legendary_Defense, non_legendary_Defense, equal_var = False, alternative = "two-sided")
if p_value_attack < 0.05:
    print("For Defense stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same")
else:
    print("Fail to reject H0 for stat Defense: -->there is enough evidence that the means of the 2 groups are different")
print('-----------------------------------------------------------------------------------------------------------------')
#----------------------------------------------------------------------------------------------------------------------#
#4. Sp. Atk	
statistic__sp_atk, p_value__sp_atk = st.ttest_ind(legendary_sp_atk, non_legendary_sp_atk, equal_var = False, alternative = "two-sided")
if p_value_attack < 0.05:
    print("For Sp. Atk	 stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same")
else:
    print("Fail to reject H0 for stat Sp. Atk	: -->there is enough evidence that the means of the 2 groups are different")
print('-----------------------------------------------------------------------------------------------------------------')
#----------------------------------------------------------------------------------------------------------------------#
#5. Sp. Def
statistic_sp_def, p_value_sp_def = st.ttest_ind(legendary_sp_def, non_legendary_sp_def, equal_var = False, alternative = "two-sided")
if p_value_attack < 0.05:
    print("For Sp. Def stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same")
else:
    print("Fail to reject H0 for stat Sp. Def	: -->there is enough evidence that the means of the 2 groups are different")
print('-----------------------------------------------------------------------------------------------------------------')
#----------------------------------------------------------------------------------------------------------------------#
#6. Speed
statistic_Speed, p_value_Speed = st.ttest_ind(legendary_Speed, non_legendary_Speed, equal_var = False, alternative = "two-sided")
if p_value_attack < 0.05:
    print("For Speed stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same")
else:
    print("Fail to reject H0 for stat Speed	: -->there is enough evidence that the means of the 2 groups are different")
print('-----------------------------------------------------------------------------------------------------------------')
#----------------------------------------------------------------------------------------------------------------------#
#6. Generation
statistic_gen, p_value_gen= st.ttest_ind(legendary_gen, non_legendary_gen, equal_var = False, alternative = "two-sided")
if p_value_attack < 0.05:
    print("For Generation stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same")
else:
    print("Fail to reject H0 for stat Generation	: -->there is enough evidence that the means of the 2 groups are different")

For HP stats, reject H0:
 --> there is insufficient evidence that the HP means of the 2 groups are the same
-----------------------------------------------------------------------------------------------------------------
For Attack stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same
-----------------------------------------------------------------------------------------------------------------
For Defense stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same
-----------------------------------------------------------------------------------------------------------------
For Sp. Atk	 stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same
-----------------------------------------------------------------------------------------------------------------
For Sp. Def stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same
-----------------------------------------------------------------------------------------------------------------
For Speed stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same
-----------------------------------------------------------------------------------------------------------------
For Generation stats, reject H0: --> there is insufficient evidence that the HP means of the 2 groups are the same

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [29]:
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
print(df.shape)
df.head()

(17000, 9)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [24]:
#Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
# we cosnider a point p1(x1, y1) and point p2(x2, y2): Euclidean: d = sqrt((x2-x1)^2 + (y2-y1)^2)


def dist_to_school(lon, lat):
    """
    dx=(Δlon)×111.32×cos(mean latitude)
    dy=(Δlat)×111.32
    
    1 degree of latitude ≈ 111.32 km
    1 degree of longitude ≈ 111.32 × cos(latitude) km
    """
    lat_school = 34
    lon_school = -118
   
    #calculate the cartisian coordinates of the school and hospital:
    dx = (lon - lon_school) * 111.32 * np.cos (np.radians((lat+lat_school)/2))
    dy = (lat - lat_school) * 111.32
   

    dist_school = np.sqrt(
        dx**2 + dy**2
    )
    return round(dist_school, 2)
    
def dist_to_hsptl(lon, lat):
    lat_hsptl = 37 
    lon_hsptl = -122
    #calculate the cartisian coordinates of the school and hospital:
    dx = (lon - lon_hsptl) * 111.32 * np.cos (np.radians((lat+lat_hsptl)/2))
    dy = (lat - lat_hsptl) * 111.32
   

    dist_hsptl = np.sqrt(
        dx**2 + dy**2
    )
    return round( dist_hsptl , 2)

In [25]:
dist_school = dist_to_school(-114.31, 34.19)
dist_hsptl = dist_to_hsptl(-114.31, 34.19)
display(dist_school)
display(dist_hsptl)

np.float64(340.82)

np.float64(763.15)

In [35]:
#Apply the 2 functions on the df
df['dist_from_school_km'] = df.apply(lambda row: dist_to_school(row['longitude'], row['latitude']), axis = 1)
df['dist_from_hospital_km'] = df.apply(lambda row: dist_to_hsptl(row['longitude'], row['latitude']), axis = 1)
df.head()
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,dist_from_school_km,dist_from_hospital_km
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353,276.042827,350.161103
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387,256.103069,198.285776
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000,0.920000,0.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000,35.060000,141.990000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000,163.030000,443.630000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000,544.935000,499.120000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000,1036.100000,822.050000

In [34]:
# Divide your dataset into houses close and far from either a hospital or school.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   longitude              17000 non-null  float64
 1   latitude               17000 non-null  float64
 2   housing_median_age     17000 non-null  float64
 3   total_rooms            17000 non-null  float64
 4   total_bedrooms         17000 non-null  float64
 5   population             17000 non-null  float64
 6   households             17000 non-null  float64
 7   median_income          17000 non-null  float64
 8   median_house_value     17000 non-null  float64
 9   dist_from_school_km    17000 non-null  float64
 10  dist_from_hospital_km  17000 non-null  float64
dtypes: float64(11)
memory usage: 1.4 MB

2053892291536

In [49]:
df['close_to_facility'] = np.where(
    (df['dist_from_school_km'] < 0.5) |
    (df['dist_from_hospital_km'] < 0.5),
    "close", "far"
)
df_close = df[df['close_to_facility'] == "close"]
df_far = df[df['close_to_facility'] == "far"]


df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,dist_from_school_km,dist_from_hospital_km,close_to_school,close_to_hospital,close_to_facility
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,340.82,763.15,far,far,far
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,328.05,739.70,far,far,far
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,319.92,769.52,far,far,far
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,319.74,771.59,far,far,far
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,320.94,775.65,far,far,far

# Hypothesis
## Null Hypothesis: price_mean near facility <= price_mean far from facility
## H1: price_mean near facility > price_mean far from facility
we use Two-sample independent T-test

In [51]:
from scipy import stats as st
stat, p_value = st.ttest_ind(df_close['median_house_value'], df_far['median_house_value'], alternative = "greater")
if p_value <0.05:
    print(f"Hypothesis rejected: {p_value} < 0.05. There is sufficient evidence that the  price of near houses is greater than far houses")
else:
    print(f"Fail to reject {p_value} >= 0.05.: there is insufficient evidence that the mean price of near houses is greater than far houses")

Fail to reject 0.7263498868187508 >= 0.05.: there is insufficient evidence that the mean price of near houses is greater than far houses